_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 8.5357
  - 47.3766
  - 15
description: A woodcut inspired map for city streets.
format: "png8:m=h:c=64"
interactivity_layer: ''
layers: null
maxzoom: 21
minzoom: 0
name: Woodcut
source: "http://openmaptiles.org/cdn.json"
styles: 
  - style.mss
  - roads.mss
  - labels.mss
  - adminlines.mss
  - highway.mss
  - label.mss
  - parks.mss
template: ''
